### ISSUE TITLE
Objects of types with no location info are rendered as "none" in results rather than their .toString()

### ISSUE THREAD

**Issue by joefarebrother** [github/vscode-codeql#575] opened 2020-09-11 11:02 UTC
**Describe the bug**
An object selected by a query, if its type doesn't define `hasLocationInfo` or `getLocation` (and isn't a primitive type), will be displayed in the results as "none", rather than its `toString`. This comes up with java's ExternalAPIsUsedWithUntrustedData query for example.

**To Reproduce**
Run the following query:
```codeql
newtype TEx = TTEx()

class Ex extends TEx {
  string toString() { result = "hi" }
}

from Ex e
select e, e.toString()
```

The results will be displayed as "none" in the first column and "hi" in the second column. 
Defining `hasLocationInfo(...)` on Ex makes it work as expected, with "hi" in both columns.
The codeql cli also displays results as expected.

**Expected behavior**
Objects should be displayed as the results of their `.toString()` predicate.

**Additional context**
VSC version: 1.49.0
Extension version: 1.3.2

**Comment by jcreedcmu** [comment] 2020-09-11 12:25
Duplicate of https://github.com/github/vscode-codeql/issues/535, but thanks for reporting, it's good to know people other than @p0 are encountering this :) This is fixed in master. We should make a new release shortly.

**Closed** 2020-09-11 12:25 UTC
Labels: VSCode, bug
