### ISSUE TITLE
Use AST Viewer with testproj databases

### ISSUE THREAD

**Issue by gsingh93** [github/vscode-codeql#1347] opened 2022-05-13 20:29 UTC
If create a test in vscode, run it, and import the generated `.testproj` database, I can do most normal operations on this database except for use the AST Viewer. When I open the file in `foo.testproj/src/path/to/code.c` and click the AST Viewer button, I get the error: "Cannot view the AST. Please select a valid source file inside a CodeQL database. (codeQL.viewAst)"

The only way I can get this to work is if I manually build a database from the command line with `codeql database create` instead of using vscode, and then open the file in the `src.zip` file, but this is inconvenient.

**Comment by aeisenberg** [comment] 2022-05-13 20:35
At this point, the extension does not fully support unzipped source folders. An easier thing to do is to simply zip the src folder in the testproj directory before importing it.

Closing this as duplicate of https://github.com/github/vscode-codeql/issues/1324

**Closed by aeisenberg** 2022-05-13 20:35 UTC
Labels: enhancement, VSCode
