### ISSUE TITLE
Compare results fails between query result and quick evaluation

### ISSUE THREAD

**Issue by rvermeulen** [github/vscode-codeql#2352] opened 2023-04-18 21:16 UTC
**Describe the bug**
When running a query and a quick-eval on a testproj, comparing the results using the `compare results` action fails with the error

```bash
Failed to show results: Schema undefined not found.
```

**Version**
CodeQL extension version: 1.8.2 
CodeQL CLI version: 2.12.6 
Platform: Darwin x64

VS Code Version: 1.77.2 (Universal)
VS Code Commit: e344f1f539a80912a0e9357cec841f36ce97a4e2

**To reproduce**
1. Create a testproj database from a failing test case.
2. Use the testproj database to run a query.
3. Quick eval part of the query that is compliant for comparing using the `compare results` command.
4. See the error message.

**Expected behavior**
Expected to see a result difference.

**Additional context**
-

**Comment by aeisenberg** [comment] 2023-05-15 22:04
Getting a chance to look at this now. The problem is that the compare view chooses the first common result set that is shared between both queries to display, but quick eval creates a custom named result set, so there is no common result set.

Two things to do:

1. Provide better error message if a matching result set can't be found.
2. Use better matching heuristics for result sets. First try to match on exact name (as now) and then try to match on the first `#`-prefixed result set in each query.

**Comment by aeisenberg** [comment] 2023-05-15 22:52
Fixed by https://github.com/github/vscode-codeql/pull/2422

**Comment by aeisenberg** [comment] 2023-05-16 20:48
Will be available in next release of the extension.

**Closed by aeisenberg** 2023-05-16 20:48 UTC
Labels: bug, VSCode
