### ISSUE TITLE
Language server sometimes stops working

### ISSUE THREAD

**Issue by gsingh93** [github/vscode-codeql#1259] opened 2022-03-30 18:27 UTC
I'm not able to reliably reproduce this issue, so I could use some suggestions for things to check or logs to collect when it happens. Here is the version of the tools I'm running:
```
CodeQL extension version: 1.6.1 
CodeQL CLI version: 2.8.4 
Platform: darwin x64
```

Occasionally, the CodeQL language server stops working, and I can't narrow down what actually causes it. I can't use code formatting or autocomplete (pressing the code formatting hot key makes vscode show `There is no formatter for 'ql' files installed`). I've observed this behavior on local databases/queries as well as remote databases/queries.

I can run queries and tests just fine.

The Output section shows the following for "CodeQL Language Server":
```
Starting CodeQL language server using CodeQL CLI: /Users/gsgx/codeql/codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
CodeQL language server started on PID: 23142
[2022-03-30 11:16:31] This is codeql execute language-server --check-errors ON_CHANGE -v --log-to-stderr
```

The language server process is running, although sometimes I see multiple language server processes running:
```
$ ps aux | grep codeql
gsgx             23139   0.1  0.7 37870524 123912   ??  S    11:16AM   0:11.55 /Users/gsgx/codeql/tools/osx64/java/bin/java -Xmx2048M --add-modules jdk.unsupported -cp /Users/gsgx/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute query-server --threads 8 -J-Xmx2048M --off-heap-ram=2048 --require-db-registration --old-eval-stats --evaluator-log /Users/gsgx/Library/Application Support/Code/User/workspaceStorage/4235255d11b506da951bd94c238e9b64/GitHub.vscode-codeql/structured-evaluator-log.json --evaluator-log-level 5 -v --log-to-stderr
gsgx             22821   0.1  0.5 40022156  85972   ??  S    11:13AM   0:22.80 /Users/gsgx/codeql/tools/osx64/java/bin/java --add-modules jdk.unsupported -cp /Users/gsgx/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute language-server --check-errors ON_CHANGE -v --log-to-stderr
gsgx             24937   0.0  0.0 34122844    872 s001  S+   11:22AM   0:00.01 grep --color=auto codeql
gsgx             23142   0.0  0.6 40022424  98692   ??  S    11:16AM   0:24.62 /Users/gsgx/codeql/tools/osx64/java/bin/java --add-modules jdk.unsupported -cp /Users/gsgx/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute language-server --check-errors ON_CHANGE -v --log-to-stderr
gsgx             23129   0.0  0.5 40013116  82440   ??  S    11:16AM   0:08.34 /Users/gsgx/codeql/tools/osx64/java/bin/java --add-modules jdk.unsupported -cp /Users/gsgx/codeql/tools/codeql.jar com.semmle.cli2.CodeQL execute cli-server -v --log-to-stderr
```

Restarting vscode doesn't seem to help. These processes are all left running when vscode closes, and manually killing them and then starting vscode also doesn't seem to help.

Then suddenly (I don't know what triggers this), the language server starts working, and in the "CodeQL Language Server" output log I see the language server JSON messages being sent back and forth.

Has this been reported before? Any suggestions for things I should test to narrow down the root cause?

**Comment by yuske** [comment] 2022-04-05 16:26
I have the same issue with the next configuration:
```
CodeQL extension version: 1.6.3 
CodeQL CLI version: 2.8.4 
Platform: win32 x64
```

I am also ready to help with the problem investigation. Any workaround would be helpful :)

**Comment by aeisenberg** [comment] 2022-04-05 17:04
Thank you for letting me know. Please post any jstacks you can generate.

**Comment by yuske** [comment] 2022-04-05 17:19
@aeisenberg I did a dump using `jstack -l <pid>`. I did not get what is `-e` argument, jstack from JDK 1.7 and 1.8 that are installed on my laptop doesn't have this argument. 

[dump.txt](https://github.com/github/vscode-codeql/files/8420488/dump.txt)

**Comment by yuske** [comment] 2022-04-05 17:24
The language service process is still stuck on my computer. I did the second dump of the same process after ~7 mins.

[dump2.txt](https://github.com/github/vscode-codeql/files/8420506/dump2.txt)

Let me know if I can do more tests.

**Comment by aeisenberg** [comment] 2022-04-05 17:47
Thank you. I am inspecting them now. The `-e` flag is supposed to give extended information about each thread, but it may not be available on earlier versions of the tool.

**Comment by gsingh93** [comment] 2022-04-06 04:11
I think this could likely be the problem, I'm working with some very large repositories. My current layout looks like this:
```
- /home/user/codeql
    - CodeQL CLI installation
- /home/user/codeql-lib
    - Checkout of https://github.com/github/codeql
- /home/user/src
    - large_repo1
        - my_codeql_pack
    - large_repo2
    - large_repo3
```

In vscode, I have a multi-root workspace with three directories: `codeql-lib`, `large_repo1`, and `large_repo2`. I only care about running queries in `large_repo1/my_codeql_pack`.

Are you saying that with the current behavior of the CodeQL CLI, it will recursively search all of the folders listed above? Would `large_repo3` be searched even if I haven't added it to my workspace? I can try moving the CLI folder to a different folder like you suggested, but maybe a CLI flag to disable this behavior would be a better option.

Also, what is the default search path and additional paths value? Can I add a CLI flag that forces CodeQL to only search for packs in `large_repo1/my_codeql_pack` (and of course the standard library in `codeql-lib`)?

**Comment by aeisenberg** [comment] 2022-04-06 17:59
Putting `codeql` in your user home directory may cause the problem I mentioned above. The first thing I would try is moving it to an otherwise empty subdirectory. Having large folders in your workspace is less likely to be an issue. The real problem is when your entire home directory is recursively searched.

We are working on ways of changing this behaviour, but we need to be careful not to break legacy setups so it is tricky.

**Comment by aeisenberg** [comment] 2022-04-11 21:28
Thanks for the feedback. It's something we are considering, specifically in the context of avoiding reading sibling directories of the current install.

I am closing this issue since I think we've determined what the cause is. Please re-open or create a new issue if you see this again.

**Closed by aeisenberg** 2022-04-11 21:28 UTC
Labels: bug, VSCode

**Comment by gsingh93** [comment] 2022-10-26 05:51
Hi @aeisenberg,

Sorry to revive this issue, but I'm still seeing some performance issues that seem to be directly related to the folders I've added to my workspace. The performance is not as bad as it was when I originally filed this issue, but I can reliably reproduce that when a folder is in my workspace, the extension doesn't even get to the Checking Query phase until about 20 seconds, whereas if I remove the folder, it only takes about 4 seconds to reach this point.

In the 4 second scenario, I only have the folder containing my queries and the CodeQL standard library in my workspace. In the 20 second scenario, I have an additional directory that is a total of 63 GB in size, although much of that is .git objects, prebuilt binaries, and build artifacts.

Would it be possible to add a configuration option to tell CodeQL which directories it should search?

**Comment by aeisenberg** [comment] 2022-10-26 16:44
I would recommend that you place a `codeql-workspace.yml` file at the root of each of your folders. See the [documentation](https://codeql.github.com/docs/codeql-cli/about-codeql-workspaces/).

You can add an explicit `ignore` chunk for all git folders, binaries and artifacts.

**Comment by gsingh93** [comment] 2022-10-26 19:19
Thanks! I was able to get this working by adding an empty `codeql-workspace.yml` in the mentioned large folder. This folder doesn't contain any QL packs and so I didn't want anything searched in it. The folder containing my queries was in a directory completely outside this large folder.

This workaround is good enough for me for now, but I won't be able to commit this file to the large repo, so it would still be nice to do this from the UI.

**Comment by aeisenberg** [comment] 2022-10-26 19:30
You could put the workspace file one directory up from your workspace folders (as long as all of your workspace folders are siblings). And then just add the directory with the codeql workspace file to your vscode workspace.
