### ISSUE TITLE
Test warnings persist after warning has been eliminated

### ISSUE THREAD

**Issue by tausbn** [github/vscode-codeql#826] opened 2021-04-13 16:54 UTC
**Describe the bug**
If I run a test (or set of tests) and it fails because of a compilation error, I get a red :warning: symbol on the test rather than a "red x" symbol. This symbol persists on the containing "test directories" even after I've fixed the error and run the test successfully. (The test file itself gets a "green checkmark" symbol.)

**To Reproduce**
1. Find a deeply-nested test.
2. Introduce a compilation error.
3. Run the test.
4. Remove compilation error.
5. Run test again.

You should now have red :warning: symbols that only go away when you hit the "refresh" button (or otherwise restart VSCode).

**Expected behavior**
The warning symbol should go away once none of its decendants have any warning symbols of their own.

**Additional context**
Seen using the latest version of the CodeQL extension, running in a Codespaces instance.

**Comment by aeisenberg** [comment] 2021-04-23 20:53
Hmmm... not able to reproduce this. I tried both inside codespaces and in a normal workspace. Is this something that you are still seeing?

**Comment by tausbn** [comment] 2021-04-23 21:19
I've found a way to reproduce it consistently, but it's slightly trickier than described above. Here are the exact steps I followed:

1. I started a fresh Codespaces instance (standard runner) off of `github/codeql` with branch `main`.
2. I installed/updated the CodeQL CLI, as this was absent.
3. I located (in the test runner) the test `/workspaces/codeql/python/ql/test/experimental/dataflow/ApiGraphs/use.ql` which I will henceforth refer to as "the test".
4. I located the file `/workspaces/codeql/python/ql/src/semmle/python/ApiGraphs.qll` which I will henceforth refer to as "the library".
5. I put a syntax error in the library in the form of a single character `d` on line 11 and saved the file.
6. I ran the test. It produced a warning.
7. I removed the syntax error and saved the file.
8. I re-ran the test.

At this point, the test passed, but its containing folders remained marked with warning symbols.

In general, I think what happens is that if you modify the test (to introduce or remove a syntax error), its test status is updated immediately (and the icons for it and its containing folders are all dimmed out), but if you make a change to a library file, this doesn't happen (and perhaps this means the test status of the folders is not marked as "stale" as it should be).

Incidentally, try introducing a syntax error to the test (say, putting `d` at the end of the file), saving, and running the test. When I do this currently, the compiler warning is displayed as a red `//` comment on the next line, which I believe has been brought up previously without a known reproduction.

**Comment by aeisenberg** [comment] 2021-04-23 21:32
Thanks for the clarification. I can reproduce. Looks like when errors are fixed in dependent files, the test hierarchy errors are not fixed.

**Comment by aeisenberg** [comment] 2021-04-23 22:17
Unfortunately, the limitation is part of the test explorer extension that we use to display the tests. There's not anything that we can do inside of the extension. This is a tricky problem to solve properly since each parent will need to store a state for each of its children and do some sort of merge. And whenever a child is finished executing, the parent node will need to update the substate just for the child that finished. This API is not available.

The best I can suggest is to click the refresh  button whenever you get into this state.

**Closed by aeisenberg** 2021-04-23 22:17 UTC
Labels: VSCode, bug, good first issue
