### ISSUE TITLE
Feature Request: Option to save query results as csv

### ISSUE THREAD

**Issue by saikatG** [github/vscode-codeql#438] opened 2020-06-09 21:25 UTC
It will be great to have an option to save the results from codeql query into a csv. Right now, I need to check where the bqrs file is, from the logs, and run `codeql bqrs decode ..` from command line.

**Comment by aeisenberg** [comment] 2020-06-10 03:36
Thanks for your feedback.

**Comment by aeisenberg** [comment] 2020-06-10 23:20
Duplicate of #342.

**Closed by aeisenberg** 2020-06-10 23:20 UTC
Labels: enhancement
