### ISSUE TITLE
[Error]: Unable to install CodeQL CLI. Error: FILE_ENDED

### ISSUE THREAD

**Issue by byteshiva** [github/vscode-codeql#245] opened 2020-02-19 14:27 UTC
**Describe the bug**
Fails to download database for CodeQL and throws the below error on vscode.
```
"Unable to install CodeQL CLI. Error: FILE_ENDED
```
**To Reproduce**
Click on + button and install database.

**Expected behavior**
It should have downloaded the database

**Additional context**

**Comment by aeisenberg** [comment] 2020-03-09 17:10
Sorry for not getting back to you sooner. 

It looks like your database is corrupted, or you are not pointing to a proper database. You should be selecting a folder with `.dbinfo` and `.qlpath` files in them at the top level.

There is more documentation here: https://help.semmle.com/codeql/codeql-for-vscode/procedures/using-extension.html

If this doesn't help, I'll need some more information from you. Can you point me to the database that you're trying to install?

**Comment by aeisenberg** [comment] 2020-03-09 17:27
Actually, on a deeper look, it's more likely that a failure to install the codeql cli in the background was the root cause of this error (perhaps a network error). If you try again and this still happens, please open the `CodeQL Extension Log` in the output view and paste the results here.

**Comment by byteshiva** [comment] 2020-03-11 13:02
> Actually, on a deeper look, it's more likely that a failure to install the codeql cli in the background was the root cause of this error (perhaps a network error). If you try again and this still happens, please open the `CodeQL Extension Log` in the output view and paste the results here.

I guess it's network error. I'll retest it and get back with detailed error log.

**Comment by jcreedcmu** [comment] 2020-05-20 17:31
Closing for now.

**Closed by jcreedcmu** 2020-05-20 17:31 UTC
Labels: bug
