### ISSUE TITLE
Can't run queries on the same DB from multiple VS Code instances

### ISSUE THREAD

**Issue by tamasvajk** [github/vscode-codeql#523] opened 2020-08-04 11:29 UTC
**Describe the bug**
"No result from server" error is displayed when trying to run a "Quick Evaluate"

**To Reproduce**
1. Start a VS Code instance and run a QL query on a given DB from a folder.
2. Start another VS Code instance and connect to the same DB from the same folder.
3. Try to run a Quick Evaluate (or any other query) from the second instance.

**Expected behavior**
I can run queries in both VS Code instances.

**Additional context**
I'm running the CodeQL Extension version 1.3.2-dev.2020.7.27.17.6.12 with codeql-cli version 2.2.4 installed with Homebrew.

**Comment by aeisenberg** [comment] 2020-08-04 15:22
Unfortunately, at this point, we don't support sharing one database across two instances of VS Code.

**Comment by aeisenberg** [comment] 2020-08-04 15:25
Duplicate of #249 and #333. Thanks for raising this issue. It is certainly something we plan to address.

**Closed by aeisenberg** 2020-08-04 15:25 UTC
Labels: VSCode, bug
